name: Generate Snake

on:
  schedule: 
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: usama6247
          outputs: dist/github-contribution-grid-snake.gif

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update snake animation"
          add: "dist/github-contribution-grid-snake.gif"
